console.log(SolarSystem.lastModifiedDate);
console.log(SolarSystem.setPlanets("Venus"));
console.log(SolarSystem.getPlanets());
console.log(SolarSystem.setActiveSpacecraft("Starship Enterprise"));
console.log(SolarSystem.getActiveSpacecraft());
console.log(SolarSystem.setPlanetsLandedOn(18));
console.log(SolarSystem.getPlanetsLandedOn());
console.log(SolarSystem.setClosestStarToSun("Deals"));
console.log(SolarSystem.getClosestStarToSun());
console.log(SolarSystem.setAgeOfSolarSystem("5 years"));
console.log(SolarSystem.getAgeOfSolarSystem());
console.log(SolarSystem.setKnownDwarfPlanets("Mars"));
console.log(SolarSystem.getKnownDwarfPlanets());